<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Creatures\Classless\**" />
    <EmbeddedResource Remove="Creatures\Classless\**" />
    <None Remove="Creatures\Classless\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Caps.Util\Caps.Util.csproj" />
    <ProjectReference Include="..\SNS.Data.DataSerializer\SNS.Data.DataSerializer.csproj" />
  </ItemGroup>

</Project>
